# Jim; I'm giving up on this docker thing. It just fails ,and I've spent about six weeks on this...
name: Docker build
on:
#  commented out since the repo doesn't allow direct pushes to master. Uncomment if this changes.
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

# -------------------- DOCKERHUB workflow --------------------------
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#
#      - name: Build and push Docker image to Dockerhub
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly:latest
# ------------------------------------------------------------------

      - name: Build and push Docker image to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO: Burde vel kunne gjøre build og tag i samme linje? Ser ut som den bare gir ny tag på linje 42?
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t 1012_shopifly_img
          docker tag 1012_shopifly_img 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1012:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1012:$rev